CREATE TABLE "CLIENTE" (
"ID_CLI" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"CEDULA_CLI" VARCHAR(15),
"NOMBRE_CLI" VARCHAR(55),
"TELEFONO_CLI" VARCHAR(15)
);

CREATE TABLE "CATEGORIA" (
"ID_CAT" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"CATEGORIA_CAT" VARCHAR(50),
"PRECIO_CAT" DECIMAL,
"MAX_PERSONAS_CAT" INT
);

CREATE TABLE "ESTADO" (
"ID_EST" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"ESTADO_EST" VARCHAR(50)
);

CREATE TABLE "HABITACION" (
"ID_HAB" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"NUMERACION_HAB" VARCHAR(5),
"PISO_HAB" INT,
"ID_CAT" INT,
"ID_EST" INT
);

CREATE TABLE "RESERVACION" (
"ID_RES" INT NOT NULL PRIMARY KEY
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1),
"ID_CLI" INT,
"ID_HAB" INT,
"FECHA_RES" DATE,
"NOCHES_RES"  INT,
"PERSONAS_RES" INT
);

ALTER TABLE HABITACION
ADD CONSTRAINT CATEGORIA_FK
FOREIGN KEY (ID_CAT)
REFERENCES CATEGORIA(ID_CAT);

ALTER TABLE HABITACION
ADD CONSTRAINT ESTADO_FK
FOREIGN KEY (ID_EST)
REFERENCES ESTADO(ID_EST);

ALTER TABLE RESERVACION
ADD CONSTRAINT CLIENTE_FK
FOREIGN KEY (ID_CLI)
REFERENCES CLIENTE(ID_CLI);

ALTER TABLE RESERVACION
ADD CONSTRAINT HABITACION_FK
FOREIGN KEY (ID_HAB)
REFERENCES HABITACION(ID_HAB);
