//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHotelli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id_res { get; set; }
        public int id_usu { get; set; }
        public int id_hab { get; set; }
        public System.DateTime fecha_ent { get; set; }
        public Nullable<System.DateTime> fecha_sal { get; set; }
        public Nullable<int> num_usuarios { get; set; }
        public int estado { get; set; }
        public Nullable<decimal> costo { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
